FROM confluentinc/cp-kafka-connect:7.5.0

ENV DEBEZIUM_VERSION=2.5.0.Final

RUN curl -sS https://repo1.maven.org/maven2/io/debezium/debezium-connector-sqlserver/${DEBEZIUM_VERSION}/debezium-connector-sqlserver-${DEBEZIUM_VERSION}-plugin.tar.gz | \
    tar -xz -C /usr/share/confluent-hub-components/

